/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.*;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.DecodeHintType;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import dao.ConnectionProvider;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Ellipse2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import utility.BDUtility;

/**
 *
 * @author Pejj
 */
public class MarkAttendance extends javax.swing.JFrame implements Runnable, ThreadFactory   {
        
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MarkAttendance.class.getName());

    private WebcamPanel panel = null;
    private Webcam webcam = null;
    private ExecutorService executor = Executors.newSingleThreadExecutor(this);
    private volatile boolean running = true;
    
    public MarkAttendance() {
        initComponents();
        BDUtility.setImage(this, "images/homebgg.jpg", 1218, 698);
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(6, 6, 6, 6, Color.GRAY));
        initWebcam();
        
        Timer timer = new Timer(1, e->updateTime());
        timer.start();
    }
    
    private void updateTime(){
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");
        lblTime.setText(simpleDateFormat.format(new Date()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        webCamPanel = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblCheckIn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        exitbtn.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        exitbtn.setText("X");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MARK ATTENDANCE");

        webCamPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DATE");

        jLabel4.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TIME");

        lblTime.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setText("TIME");

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblCheckIn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 401, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(242, 242, 242)
                        .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(webCamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(149, 149, 149)
                                            .addComponent(jLabel4))))
                                .addGap(58, 58, 58))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(96, 96, 96))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(webCamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        running = false;
if (webcam != null && webcam.isOpen()) webcam.close();
dispose();

    }//GEN-LAST:event_exitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MarkAttendance().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCheckIn;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPanel webCamPanel;
    // End of variables declaration//GEN-END:variables
@Override


public Thread newThread(Runnable r) {
    Thread t = new Thread(r);
    t.setDaemon(true);
    return t;
}

    Map<String, String> resultMap = new HashMap<String, String>();
    
    @Override
    public void run() {
         long lastScanTime = 0;

    while (running) {
        try {
            Thread.sleep(150); // faster loop

            if (System.currentTimeMillis() - lastScanTime < 300) continue;
            lastScanTime = System.currentTimeMillis();

            if (webcam.isOpen()) {
                BufferedImage image = webcam.getImage();
                if (image == null) continue;

                // Resize image for faster decoding
                BufferedImage resized = new BufferedImage(480, 360, BufferedImage.TYPE_INT_RGB);
                Graphics2D g = resized.createGraphics();
                g.drawImage(image, 0, 0, 480, 360, null);
                g.dispose();

                LuminanceSource source = new BufferedImageLuminanceSource(resized);
                BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));

                Map<DecodeHintType, Object> hints = new HashMap<>();
                hints.put(DecodeHintType.TRY_HARDER, Boolean.FALSE);
                hints.put(DecodeHintType.POSSIBLE_FORMATS, Arrays.asList(BarcodeFormat.QR_CODE));

                try {
                    Result result = new MultiFormatReader().decode(bitmap, hints);
                    if (result != null) {
                        System.out.println("Raw QR content: " + result.getText());

                        String jsonString = result.getText();
                        Gson gson = new Gson();
                        java.lang.reflect.Type type = new TypeToken<Map<String, String>>() {}.getType();
                        Map<String, String> parsedMap = gson.fromJson(jsonString, type);

                        resultMap.clear();
                        resultMap.putAll(parsedMap);

                        String finalPath = BDUtility.getPath("images\\" + resultMap.get("id") + ".jpg");
                        CircularImageFrame(finalPath);
                    }
                } catch (NotFoundException ex) {
                    // No QR code found in this frame
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
  private void initWebcam() {
    org.apache.log4j.BasicConfigurator.configure();

    Dimension size = WebcamResolution.QVGA.getSize();
    webcam = Webcam.getDefault();

    if (webcam != null) {
       webcam.setViewSize(WebcamResolution.VGA.getSize());

        panel = new WebcamPanel(webcam);
        panel.setPreferredSize(new Dimension(689, 518));
        panel.setFPSDisplayed(true);

        webCamPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        webCamPanel.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 689, 518));
        webCamPanel.revalidate();
        webCamPanel.repaint();

        executor.execute(this);
    } else {
        System.out.println("No webcam detected!");
        JOptionPane.showMessageDialog(this, "No webcam found!");
    }
  } 

  private void stopWebcam(){
      if(webcam!=null && webcam.isOpen()){
          webcam.close();
      }
  }
     
    private BufferedImage imagee = null;
   private void CircularImageFrame(String imagePath) {
    try {
        Connection con = ConnectionProvider.getCon();
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("select * from student where id ='" + resultMap.get("id") + "'");
        
        if (!rs.next()) {
            showPopUpForCertainDuration("Student is not Registered or Deleted", "Invalid Qr", JOptionPane.ERROR_MESSAGE);
            return;
        }

      imagee = null;
      File imageFile = new File(imagePath);
      if (imageFile.exists()) {
         try {
        imagee = ImageIO.read(imageFile);
        imagee = createCircularImage(imagee);
        ImageIcon icon = new ImageIcon(imagee);
        lblImage.setIcon(icon);
     } catch (Exception ex) {
        ex.printStackTrace();
    }
      } else {
           BufferedImage imageeee = new BufferedImage(300, 300, BufferedImage.TYPE_INT_ARGB);
            Graphics2D g2d = imageeee.createGraphics();

           g2d.setColor(Color.BLACK);
          g2d.fillOval(25, 25, 250, 250);

         g2d.setFont(new Font("Serif", Font.BOLD, 250));
          g2d.setColor(Color.WHITE);
          String name = String.valueOf(resultMap.get("name"));
           if (name != null && !name.isEmpty()) {
             g2d.drawString(String.valueOf(name.charAt(0)).toUpperCase(), 75, 225);
          }
          g2d.dispose();

      ImageIcon imageIconn = new ImageIcon(imageeee);
      lblImage.setIcon(imageIconn);
      this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      this.pack();
      this.setLocationRelativeTo(null); 
      this.setVisible(true);        
    }
      lblName.setHorizontalAlignment(JLabel.CENTER);
      lblName.setText(resultMap.get("name"));
      if(!checkIn()){
          return;
      }
       } catch (Exception ex) {
        ex.printStackTrace();
     }
  }

    
   private void showPopUpForCertainDuration(String popUpMessage, String popUpHeader, Integer iconId) throws HeadlessException {
    final JOptionPane optionPane = new JOptionPane(popUpMessage, iconId);
    final JDialog dialog = optionPane.createDialog(popUpHeader);
    dialog.setModal(false); // Allow the dialog to close automatically

    Timer timer = new Timer(5000, new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            dialog.setVisible(false);
            dialog.dispose();
            clearStudentDetails();
        }

        private void clearStudentDetails() {
            lblCheckIn.setText("");
            lblCheckIn.setBackground(null);
             lblCheckIn.setForeground(null);
              lblCheckIn.setOpaque(false);
               lblName.setText("");
               lblImage.setIcon(null);
        }
    });
    timer.setRepeats(false); // Ensure it only runs once
    timer.start();
    dialog.setVisible(true);
}


    private BufferedImage createCircularImage(BufferedImage imagee) {
       int diameter = 285;
    BufferedImage resizedImage = new BufferedImage(diameter, diameter, BufferedImage.TYPE_INT_ARGB);
    Graphics2D g2 = resizedImage.createGraphics();
    g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
    g2.drawImage(imagee, 0, 0, diameter, diameter, null);
    g2.dispose();

    BufferedImage circularImage = new BufferedImage(diameter, diameter, BufferedImage.TYPE_INT_ARGB);
    g2 = circularImage.createGraphics();
    Ellipse2D.Double circle = new Ellipse2D.Double(0, 0, diameter, diameter);
    g2.setClip(circle);
    g2.drawImage(resizedImage, 0, 0, null);
    g2.dispose();
    return circularImage;
       
    }

    private boolean checkIn() throws SQLException {
        String popUpHeader = null;
    String popUpMessage = null;
    Color color = null;

    Connection con = ConnectionProvider.getCon();
    Statement st = con.createStatement();

    LocalDate currentDate = LocalDate.now();
    DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

    LocalDateTime currentDateTime = LocalDateTime.now();
    DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    // Check if student already checked in today
    ResultSet rs = st.executeQuery(
        "SELECT * FROM studentattendance WHERE date='" + currentDate.format(dateFormatter) + 
        "' AND studentId='" + resultMap.get("id") + "'");
        
    if(rs.next()) {
        // Student already checked in today
        String checkInTime = rs.getString("timeIn");
        LocalDateTime checkInLocalDateTime = LocalDateTime.parse(checkInTime, dateTimeFormatter);
        Duration duration = Duration.between(checkInLocalDateTime, currentDateTime);
        
        long hours = duration.toHours();
        long minutes = duration.minusHours(hours).toMinutes();
        long seconds = duration.minusHours(hours).minusMinutes(minutes).getSeconds();

        if (!(hours > 0 || (hours == 0 && minutes >= 5))) {
            long remainingMinutes = 4 - minutes;
            long remainingSeconds = 60 - seconds;

            popUpMessage = String.format("Your work duration is less than 5 minutes\nYou can check out after: %d minutes and %d seconds", 
            remainingMinutes, remainingSeconds);
            popUpHeader = "Duration Warning";

            showPopUpForCertainDuration(popUpMessage, popUpHeader, JOptionPane.WARNING_MESSAGE);
            return false;
        } else {
            popUpMessage = "Already checked Attendance in today at " + checkInTime;
            popUpHeader = "Already Attedance today";
            showPopUpForCertainDuration(popUpMessage, popUpHeader, JOptionPane.WARNING_MESSAGE);
            return false;
        }
    } else {
        // First check-in today - Insert new record
        
        Connection connection = ConnectionProvider.getCon();
   String insertQuery = "INSERT INTO studentattendance (studentId, name, date, timeIn, section) VALUES (?,?,?,?,?)";
PreparedStatement preparedStatement = connection.prepareStatement(insertQuery);

preparedStatement.setString(1, resultMap.get("id"));
preparedStatement.setString(2, resultMap.get("name"));
preparedStatement.setString(3, currentDate.format(dateFormatter));
preparedStatement.setString(4, currentDateTime.format(dateTimeFormatter));
preparedStatement.setString(5, resultMap.get("section")); 


    

        preparedStatement.executeUpdate();
        preparedStatement.close();
        connection.close();
        
        popUpHeader = "Attedance Successful";
        popUpMessage = "Attedance in at " + currentDateTime.format(dateTimeFormatter);
        color = Color.GREEN;

        lblCheckIn.setHorizontalAlignment(JLabel.CENTER);
        lblCheckIn.setText(popUpHeader);
        lblCheckIn.setForeground(color);
        lblCheckIn.setBackground(Color.DARK_GRAY);
        lblCheckIn.setOpaque(true);
        
        showPopUpForCertainDuration(popUpMessage, popUpHeader, JOptionPane.INFORMATION_MESSAGE);
        
        rs.close();
        st.close();
        con.close();
        
        return true;
     }
    }

    @Override
   public void paint(Graphics g) {
    super.paint(g);
    if (imagee != null) {
        g.drawImage(imagee, 0, 0, null);
      }
    }
}
   
