/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import dao.ConnectionProvider;
import java.sql.*;
import java.util.Arrays;
import java.util.List;
import java.util.ArrayList;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.lang.reflect.Array;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import static org.apache.xmlbeans.impl.schema.StscState.end;
import static org.apache.xmlbeans.impl.schema.StscState.start;
import utility.BDUtility;

/**
 *
 * @author Pejj
 */
public class ViewAttendance extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewAttendance.class.getName());

    /**
     * Creates new form ViewAttendance
     */
    public ViewAttendance() {
        initComponents();
         BDUtility.setImage(this, "images/homebgg.jpg", 1020, 528);
         this.getRootPane().setBorder(BorderFactory.createMatteBorder(6, 6, 6, 6, Color.GRAY));
         
         dateChooserFrom.setDateFormatString("yyyy-MM-dd");
         dateChooserTo.setDateFormatString("yyyy-MM-dd");
         setupGenerateExcel(generateBtn, studentTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        exitbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        dateChooserFrom = new com.toedter.calendar.JDateChooser();
        dateChooserTo = new com.toedter.calendar.JDateChooser();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        presentLBL = new javax.swing.JLabel();
        absentLBL = new javax.swing.JLabel();
        lblPresent = new javax.swing.JLabel();
        lblAbsent = new javax.swing.JLabel();
        generateBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sitka Subheading", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VIEW ATTENDANCE");

        exitbtn.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        exitbtn.setText("X");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(studentTable);

        dateChooserFrom.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateChooserFromPropertyChange(evt);
            }
        });

        dateChooserTo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateChooserToPropertyChange(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TO: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FROM:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SEARCH: ");

        presentLBL.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        presentLBL.setForeground(new java.awt.Color(255, 255, 255));
        presentLBL.setText("PRESENT:");

        absentLBL.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        absentLBL.setForeground(new java.awt.Color(255, 255, 255));
        absentLBL.setText("ABSENT:");

        lblPresent.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblPresent.setForeground(new java.awt.Color(51, 255, 51));
        lblPresent.setText("----------");

        lblAbsent.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblAbsent.setForeground(new java.awt.Color(255, 0, 0));
        lblAbsent.setText("----------");

        generateBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        generateBtn.setText("GENERATE TO EXCEL");

        removeBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        removeBtn.setText("REMOVE");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(252, 252, 252)
                        .addComponent(exitbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(presentLBL)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblPresent))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(absentLBL)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblAbsent)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(dateChooserFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(dateChooserTo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(generateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(removeBtn)))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exitbtn)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dateChooserFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateChooserTo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(presentLBL)
                            .addComponent(lblPresent))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(absentLBL)
                            .addComponent(lblAbsent))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeBtn))
                .addGap(17, 17, 17))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
         this.dispose();
    }//GEN-LAST:event_exitbtnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
      loadDataInTable();
    }//GEN-LAST:event_formComponentShown

      
    private void dateChooserFromPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateChooserFromPropertyChange
         loadDataInTable();
    }//GEN-LAST:event_dateChooserFromPropertyChange

    private void dateChooserToPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateChooserToPropertyChange
          loadDataInTable();
    }//GEN-LAST:event_dateChooserToPropertyChange

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
       loadDataInTable();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        int selectedRow = studentTable.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Please select a row to delete.", "No Selection", JOptionPane.WARNING_MESSAGE);
        return;
    }

    TableModel model = studentTable.getModel();
    String lrn = model.getValueAt(selectedRow, 0).toString(); // Assuming LRN is the primary key

    int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this student?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            Connection con = ConnectionProvider.getCon();
            PreparedStatement ps = con.prepareStatement("DELETE FROM studentattendance WHERE id = ?");
            ps.setString(1, lrn);
            int result = ps.executeUpdate();

            if (result > 0) {
                ((DefaultTableModel) studentTable.getModel()).removeRow(selectedRow);
                JOptionPane.showMessageDialog(null, "Student deleted successfully.");
            } else {
                JOptionPane.showMessageDialog(null, "Failed to delete student.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "An error occurred while deleting.", "EDrror", JOptionPane.ERROR_MESSAGE);
        }
      }      
    }//GEN-LAST:event_removeBtnActionPerformed
public static void setupGenerateExcel(JButton generateBtn, JTable attendanceTable) {
    generateBtn.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            Workbook workbook = new XSSFWorkbook();
            Sheet sheet = workbook.createSheet("Attendance");

            // Header row
            Row headerRow = sheet.createRow(0);
            for (int i = 0; i < attendanceTable.getColumnCount(); i++) {
                Cell cell = headerRow.createCell(i);
                cell.setCellValue(attendanceTable.getColumnName(i));
            }

            // Data rows
            for (int i = 0; i < attendanceTable.getRowCount(); i++) {
                Row row = sheet.createRow(i + 1);
                for (int j = 0; j < attendanceTable.getColumnCount(); j++) {
                    Object value = attendanceTable.getValueAt(i, j);
                    row.createCell(j).setCellValue(value != null ? value.toString() : "");
                }
            }
        // Step 1: Get all student names
Set<String> allStudents = new HashSet<>();
try (Connection con = ConnectionProvider.getCon();
     Statement st = con.createStatement();
     ResultSet rs = st.executeQuery("SELECT name FROM student")) {
    while (rs.next()) {
        allStudents.add(rs.getString("name"));
    }
} catch (Exception ex) {
    JOptionPane.showMessageDialog(null, "Error loading student list: " + ex.getMessage());
}

// Step 2: Group present students by date
Map<String, Set<String>> presentByDate = new HashMap<>();
for (int i = 0; i < attendanceTable.getRowCount(); i++) {
    String date = attendanceTable.getValueAt(i, 4).toString(); // formatted date
    String name = attendanceTable.getValueAt(i, 2).toString(); // student name
    presentByDate.computeIfAbsent(date, k -> new HashSet<>()).add(name);
}

// Step 3: Write summary with absent names
int summaryStartRow = attendanceTable.getRowCount() + 2;
Row header = sheet.createRow(summaryStartRow++);
header.createCell(0).setCellValue("Date");
header.createCell(1).setCellValue("Present");
header.createCell(2).setCellValue("Absent Count");
header.createCell(3).setCellValue("Absent Names");

// Enable wrap text style
CellStyle wrapStyle = workbook.createCellStyle();
wrapStyle.setWrapText(true);

for (Map.Entry<String, Set<String>> entry : presentByDate.entrySet()) {
    String date = entry.getKey();
    Set<String> presentStudents = entry.getValue();

    Set<String> absentStudents = new HashSet<>(allStudents);
    absentStudents.removeAll(presentStudents);

    Row row = sheet.createRow(summaryStartRow++);
    row.createCell(0).setCellValue(date);
    row.createCell(1).setCellValue(presentStudents.size());
    row.createCell(2).setCellValue(absentStudents.size());

    String absentNames = String.join("\n", absentStudents);
    Cell absentCell = row.createCell(3);
    absentCell.setCellValue(absentNames);
    absentCell.setCellStyle(wrapStyle);
}

            // Save to file
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Save Excel File");
            int userSelection = fileChooser.showSaveDialog(null);
            if (userSelection == JFileChooser.APPROVE_OPTION) {
                File fileToSave = fileChooser.getSelectedFile();
                try (FileOutputStream fileOut = new FileOutputStream(fileToSave + ".xlsx")) {
                    workbook.write(fileOut);
                    workbook.close();
                    JOptionPane.showMessageDialog(null, "Excel file saved to: " + fileToSave.getAbsolutePath());
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Error saving Excel file: " + ex.getMessage());
                }
            }
        }
    });
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewAttendance().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel absentLBL;
    private com.toedter.calendar.JDateChooser dateChooserFrom;
    private com.toedter.calendar.JDateChooser dateChooserTo;
    private javax.swing.JButton exitbtn;
    private javax.swing.JButton generateBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAbsent;
    private javax.swing.JLabel lblPresent;
    private javax.swing.JLabel presentLBL;
    private javax.swing.JButton removeBtn;
    private javax.swing.JTable studentTable;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

   private void loadDataInTable() {
    List<String> columns = Arrays.asList("id", "studentId", "name", "gender", "date", "timeIn", "section");

    String searchText = txtSearch.getText().replaceAll("\\p{C}", "").trim().toLowerCase();

    LocalDate fromDate = null;
    Date fromDateRaw = dateChooserFrom.getDate();
    if (fromDateRaw != null) {
        fromDate = fromDateRaw.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    }

    LocalDate toDate = null;
    Date toDateRaw = dateChooserTo.getDate();
    if (toDateRaw != null) {
        toDate = toDateRaw.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    }

    Long daysBetween = (fromDate != null && toDate != null) ? countWeekdays(fromDate, toDate) : null;

    StringBuilder sql = new StringBuilder(
        "SELECT sa.id, sa.studentId, s.name, s.gender, sa.date, sa.timeIn, sa.section " +
        "FROM studentAttendance sa " +
        "JOIN student s ON sa.studentId = s.id"
    );

    List<String> conditions = new ArrayList<>();
    if (!searchText.isEmpty()) {
        conditions.add("(LOWER(s.name) LIKE '%" + searchText + "%' OR sa.studentId LIKE '%" + searchText + "%')");
    }
    if (fromDate != null && toDate != null) {
        conditions.add("DATE(sa.date) BETWEEN '" + fromDate + "' AND '" + toDate + "'");
    } else if (fromDate != null) {
        conditions.add("DATE(sa.date) = '" + fromDate + "'");
    }

    if (!conditions.isEmpty()) {
        sql.append(" WHERE ").append(String.join(" AND ", conditions));
    }

    System.out.println("SQL Query: " + sql.toString());

    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(columns.toArray());
    studentTable.setModel(model);

    try (Connection con = ConnectionProvider.getCon();
         Statement st = con.createStatement();
         ResultSet rs = st.executeQuery(sql.toString())) {

        Long presentCount = 0L;
        Long absentCount = 0L;
        boolean recordFound = false;

        while (rs.next()) {
            recordFound = true;
            List<Object> row = new ArrayList<>();
            row.add(rs.getString("id"));
            row.add(rs.getString("studentId"));
            row.add(rs.getString("name"));
            row.add(rs.getString("gender"));

            // Convert UTC date and time to Asia/Manila timezone
            LocalDate rawDate = LocalDate.parse(rs.getString("date"));
            LocalTime rawTime = LocalTime.parse(rs.getString("timeIn"));

            ZoneId dbZone = ZoneId.of("UTC");
            ZoneId localZone = ZoneId.of("Asia/Manila");

            LocalDateTime utcDateTime = LocalDateTime.of(rawDate, rawTime);
            ZonedDateTime localDateTime = utcDateTime.atZone(dbZone).withZoneSameInstant(localZone);

            // Format for display
            String formattedDate = localDateTime.format(DateTimeFormatter.ofPattern("MMM dd, yyyy"));
            String formattedTime = localDateTime.format(DateTimeFormatter.ofPattern("hh:mma")).toLowerCase();

            row.add(formattedDate);
            row.add(formattedTime);
            row.add(rs.getString("section")); // Correct section value

            model.addRow(row.toArray());
            presentCount++;
        }

        if (recordFound) {
            lblPresent.setVisible(true);
            lblAbsent.setVisible(true);
            presentLBL.setVisible(true);
            absentLBL.setVisible(true);

            lblPresent.setText(presentCount.toString());
            if (daysBetween != null && daysBetween > 0) {
                absentCount = daysBetween - presentCount;
            }
            lblAbsent.setText(absentCount.toString());
        } else {
            lblPresent.setVisible(false);
            lblAbsent.setVisible(false);
            presentLBL.setVisible(false);
            absentLBL.setVisible(true);
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Something went wrong.");
        ex.printStackTrace();
    }
}
    private Long countWeekdays(LocalDate fromDate, LocalDate toDate) {
    long count = 0;
    LocalDate date = fromDate;
    while (date.isBefore(toDate) || date.equals(toDate)) {
        if (!(date.getDayOfWeek() == DayOfWeek.SATURDAY || date.getDayOfWeek() == DayOfWeek.SUNDAY)) {
            count++;
        }
        date = date.plusDays(1);
    }
    return count;
  }
}
  

    
    



